name: basic
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt-get update && sudo apt-get install -y cmake g++ libbenchmark-dev
      - run: mkdir build && cmake -B build -S . && cmake --build build 
      - uses: actions/upload-artifact@v4
        with:
          name: binares
          path: |
            build/main
            build/tests
            build/bench_example
      
  tests:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: binares
      - run: chmod +x tests && ./tests

  run:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: binares
      - run: chmod +x main && ./main 3 6

  ench:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: binares
      - run: chmod +x bench_example && ./bench_example arg1 arg2 arg3


  